export const EMP = {
    GET: 'GET',
    ADD: 'ADD',
    STORE: 'STORE',
    DELETE: 'DELETE',
    UPDATE: 'UPDATE',
    IS_DONE: 'IS_DONE',
    IS_ERROR: 'IS_ERROR',
    IS_LOADING: 'IS_LOADING',
    IS_DONE_ACTION: 'IS_DONE_ACTION',
    IS_ERROR_ACTION: 'IS_ERROR_ACTION',
    IS_LOADING_ACTION: 'IS_LOADING_ACTION',
}