export const EMP = {
    IS_LOADING: 'IS_LOADING',
    IS_ERROR: 'IS_ERROR',
    IS_DONE: 'IS_DONE',
    IS_LOADING_ACTION: 'IS_LOADING_ACTION',
    IS_ERROR_ACTION: 'IS_ERROR_ACTION',
    IS_DONE_ACTION: 'IS_DONE_ACTION',
    ADD: 'ADD',
    DELETE: 'DELETE',
    UPDATE: 'UPDATE',
    GET: 'GET',
    STORE: 'STORE'
}